### ISSUE TITLE
Not an issue but...

### ISSUE THREAD

**Issue by korewatori** [pbrln/GTAV-Tunables#3]
How did you find the encryption key to decrypt the json? Would love to know, I've been thinking about making a tool like this for the game's other files. Also, I was unsure if you'll even see this since your last repo was in 2019.

**Comment by pbrln** [comment]
Hey there,
I really just used some random tool I found to find AES key like data structures from a memory dump I took and then tried out a few keys that made sense.  
I don't remember which program exactly I used but judging by a quick google search I think it may have been this one:
https://github.com/mmozeiko/aes-finder

Good luck with your tool 👍

**Comment by korewatori** [comment]
Thanks a lot! Sorry for opening this again, but do you have a x64 build of that? VS is being stubborn and refusing to let me upgrade the project toolset from VS2013

**Comment by korewatori** [comment]
(bump, idk if you saw this but I wanted to know if that's alright)

**Comment by pbrln** [comment]
Hey there,
sorry for the late response. If you still need help send me a request on discord: @ECB2#6494
